const defaultTheme = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    // Or if using `src` directory:
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/modules/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#120F1D",
        secondary: "#DE1EFD",
        "light-white": "#777E90",
        "transparent-color": "rgba(27, 28, 32, 0.6)",
        "transparent-deep": "rgba(35, 38, 47, 0.78)",
        "transparent-1": "rgba(217, 217, 217, 0.1)",
        "transparent-2": "rgba(202, 198, 221, 0.10)",
        "transparent-3": "rgba(255, 255, 255, 0.10)",
        "transparent-error": "rgba(255, 59, 48, 0.10)",
        "transparent-secondary": "rgba(70, 25, 78, 0.80)",
        "light-2": "#ECECEC",
        "light-3": "#E6E8EC",
        "light-4": "#FCFCFD",
        harsh: "#353945",
        "light-harsh": "#777E91",
        dark: "#141416",
        "dark-2": "#2F3941",
        "dark-3": "#212531",
        "dark-4": "#01001D",
        "light-secondary": "#8076fe",
        "deep-secondary": "#1C182D",
        "gray-600": "#68737D",
        "gray-300": "#D8DCDE",
        "gray-400": "#B7BECB",
        "neutrals-5": "#B1B5C4",
        "neutrals-6": "#343745",
        "neutrals-7": "#202E49",
        blue: "#9099FC",
        success: "#41AD73",
        "success-2": "#00E3B4",
        "success-3": "#15CC35",
        danger: "#FF3B30",
        "danger-2": "#FF7F7B",
      },
      fontFamily: {
        sans: ["Aeonik Pro", ...defaultTheme.fontFamily.sans],
        "aeonik-pro": "Aeonik Pro",
        "aeonik-pro-bold": "Aeonik Pro Bold",
        "aeonik-fono": "Aeonik Fono",
        "aeonik-fono-bold": "Aeonik Fono Bold",
        poppins: "Poppins",
        "poppins-semi-bold": "Poppins Semi Bold",
        "poppins-light": "Poppins Light",
        "poppins-bold": "Poppins Bold",
        "dm-sans": "DM Sans",
        "dm-sans-bold": "DM Sans Bold",
        "sf-pro-text": "SF Pro Text",
        "sf-pro-text-semi-bold": "SF Pro Text Semibold",
        "sf-pro-text-bold": "SF Pro Text Bold",
        "ibm-plex-mono": "IBM Plex Mono",
        "ibm-plex-semi-bold": "IBM Plex Mono Semi Bold",
        "noto-sans": "Noto Sans",
        inter: "Inter",
        "inter-light": "Inter Light",
      },
      fontSize: {
        heading: "30px",
        "sub-heading": "23px",
        "semi-heading": "20px",
        lg: "17px",
        "caption-0.5": "10px",
        "caption-1": "12px",
        "caption-2": "13px",
        "caption-3": "15px",
      },
      backgroundImage: {
        "theme-bg": "url('/theme-bg.png')",
        "home-stat-bg": "url('/hom-stats.png')",
        "mark-bg": "url('/mark.png')",
        // "transparent-color": "rgba(27, 28, 32, 0.6)",
        "secondary-gradient":
          "linear-gradient(98.88deg, #8C01FA 31%, #EB08A4 102.28%)",
        "text-clip": "linear-gradient(152deg, #8C01FA 32.29%, #EB08A4 100%)",
        "background-card-gradient":
          "linear-gradient(98.88deg, #8C01FA 31%, #EB08A4 102.28%),linear-gradient(0deg, #8D0EA2, #8D0EA2)",
      },

      lineHeight: {
        "leading-24": "24px",
      },
    },
  },
  plugins: [],
};
